### PR TITLE
Fix login with username and password

### LINKED ISSUE #274: Exiting due to Result.InvalidPassword when logging in without enterering a 2FA code
### Summary

When you log in without passing a `shared_secret` and attempt to confirm login using the app it fails

### Reproduction Steps

```py
@type.__call__
class client(steam.Client):
	async def code(self):
		await asyncio.sleep(10)  # confirm using the app
		return ""

client.run("username", "password")
```

### Expected Results

No error

### Actual Results

You get a ConnectionClosed. Interestingly the refresh_token produced is still valid to login with.

### System Information

I don't get paid enough for this

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

### LINKED ISSUE #307: Unable to login to Steam using username and password
### Summary

Unable to login to Steam

### Reproduction Steps

1. Attempt to login using the steam.login() function with shared_secret.
2. Receive a prompt for steam guard code even though shared_secret was provided.
3. Enter the steam guard code.
4. Observe that the program hangs indefinitely.

Here is the code snippet:
```
logger.info("正在登录...")
asyncio.run(
    client.login(
        acc.get("steam_username"),
        acc.get("steam_password"),
        shared_secret=acc.get("steam_shared_secret"),
        identity_secret=acc.get("steam_identity_secret"),
    )
)
```

### Expected Results

The program should login successfully without prompting for steam guard code when shared_secret is provided.

### Actual Results

The program prompts for steam guard code even with shared_secret and hangs indefinitely after entering the code.

### System Information

```
root@jiajiaxd-do-us-sf:~/Steamauto# python3 -m steam
python version: 3.10.12
steam.py version: 1.0.0a2898+g56e9ca3
aiohttp version: 3.8.5
betterproto version: 2.0.0b6
operating system info: Linux-5.15.120-bbrplus-x86_64-with-glibc2.35
```

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

### PR DESCRIPTION
**Pull request by somespecialone**
## Summary

Fix infinite waiting when try to login with username and password. Fix `InvalidPassword` response on `ClientLogon` attempt.
Fixes #274 
Fixes #307 

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by somespecialone** [comment]
I just remove `async for` cycle to make code less verbose as we now use only first `cm` from iterator.

**Comment by Gobot1234** [comment]
Not iterating over the servers is a bug, if you don't want to fix it though I can before merging

**Comment by somespecialone** [comment]
Ok. But why we need iteration? We never skip it or go for second spin.

**Comment by Gobot1234** [comment]
I originally wrote it with the intention of having it iterate over the pool of CMs until one of them did work. Clearly I never got round to implementing this, hence why I'm saying its a bug.

**Comment by Gobot1234** [comment]
Thanks! Merged https://github.com/Gobot1234/steam.py/commit/125c0ab491353e96b0a7c41672a9d9a46f0e4999

**Pull request closed without merging**
